# Generated by Django 6.1.1 on 2026-10-05 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_booking', '0003_unique_user_email'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='occupancy',
            new_name='room_bookin_room_id_0a5455_idx',
            old_name='room_bookin_room_id_4d5f5d_idx',
        ),
        migrations.RenameIndex(
            model_name='occupancy',
            new_name='room_bookin_user_id_40a7c2_idx',
            old_name='room_bookin_user_id_0a1f7b_idx',
        ),
    ]
